### ISSUE TITLE
Can't Give item to player

### ISSUE THREAD

**Issue by wasuryanto3** [iONDegen/ps-inventory#8]
How to fix it?

**Comment by iONDegen** [comment]
I pushed an update to fix, Right click and item and you should be able to see the inventory options!

**Comment by wasuryanto3** [comment]
Yes, I did that but nothing happened.

**Comment by BrendanWolf** [comment]
Still not working, I get an error 

SCRIPT ERROR: @ps-inventory/server/main.lua:2280: attempt to compare nil with number
